include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**.config.dart"
    - "*_test.dart"
    - "**/generated_plugin_registrant.dart"
