name: ar_furniture_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  vector_math: ^2.1.4
  equatable: ^1.1.0
  ar_core: ^0.0.2+7
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  material_design_icons_flutter: ^6.0.7096
  shimmer: ^2.0.0
  badges: ^3.0.2
  smooth_page_indicator: ^1.0.1
  cloud_firestore: ^4.3.2
  google_sign_in: ^5.4.4
  flutter_riverpod: ^2.2.0
  flutter_svg: ^2.0.1
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_facebook_auth: ^5.0.7
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  assets:
    - assets/images/
    - assets/lottie/
