// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8zMDtRFBQiBJTDhfMbJQLf2WkfSD5ofU',
    appId: '1:549241961575:web:b975ceaa3ac39be419e8c2',
    messagingSenderId: '549241961575',
    projectId: 'ar-furniture-app-74112',
    authDomain: 'ar-furniture-app-74112.firebaseapp.com',
    storageBucket: 'ar-furniture-app-74112.appspot.com',
    measurementId: 'G-2ZJ3C259WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ZO7wFPIU1iHmSEKWUHVfvECcdj9mxvM',
    appId: '1:549241961575:android:25fc1f4472644b0119e8c2',
    messagingSenderId: '549241961575',
    projectId: 'ar-furniture-app-74112',
    storageBucket: 'ar-furniture-app-74112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo59twGZOhTzgiQ5x51pdNu3yF8Hl_MXw',
    appId: '1:549241961575:ios:b631907da109c41519e8c2',
    messagingSenderId: '549241961575',
    projectId: 'ar-furniture-app-74112',
    storageBucket: 'ar-furniture-app-74112.appspot.com',
    iosClientId: '549241961575-hlhr230h9j56jdtkha146vgpsl4dll8j.apps.googleusercontent.com',
    iosBundleId: 'com.codermonkeys.arFurnitureApp',
  );
}
